// Code generated by "stringer -type=Suit,Rank"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Spade-0]
	_ = x[Diamond-1]
	_ = x[Club-2]
	_ = x[Heart-3]
}

const _Suit_name = "SpadeDiamondClubHeart"

var _Suit_index = [...]uint8{0, 5, 12, 16, 21}

func (i Suit) String() string {
	if i >= Suit(len(_Suit_index)-1) {
		return "Suit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Suit_name[_Suit_index[i]:_Suit_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Seven-1]
	_ = x[Eight-2]
	_ = x[Queen-3]
	_ = x[King-4]
	_ = x[Ten-5]
	_ = x[Ace-6]
	_ = x[Nine-7]
	_ = x[Jack-8]
}

const _Rank_name = "SevenEightQueenKingTenAceNineJack"

var _Rank_index = [...]uint8{0, 5, 10, 15, 19, 22, 25, 29, 33}

func (i Rank) String() string {
	i -= 1
	if i >= Rank(len(_Rank_index)-1) {
		return "Rank(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Rank_name[_Rank_index[i]:_Rank_index[i+1]]
}
